01.Cinema_Info.Web/Controllers/ArtisController.cs
using System;
using _02.Cinema_info.DataAccess;
using _03.Cinema_Info.ViewModel;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;

namespace _01.Cinema_Info.Web.Controllers
{
    public class ArtisController : Controller
    {
        // GET: Artis
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddToFilm(int idFilm)
        {
            ViewBag.idFilm = idFilm;
            ViewBag.judulFilm = FilmDataAccess.GetById(idFilm).nama_film;
            List<ArtisViewModel> artis = ArtisDataAccess.GetAll();
            foreach (var item in artis)
            {
                item.belum_masuk_list = DetailArtisFilmDataAccess.CheckBelumAda(idFilm, item.id_artis_pk);
            }
            return PartialView("AddToFilm", artis);
        }

        public ActionResult AddPeran(int idFilm, int idArtis)
        {
            ViewBag.idFilm = idFilm;
            ViewBag.idArtis = idArtis;
            ViewBag.judulFilm = FilmDataAccess.GetById(idFilm).nama_film;
            ViewBag.namaArtis = ArtisDataAccess.GetById(idArtis).nama_artis;


            return PartialView("AddPeran");
        }

        [HttpPost]
        public ActionResult AddToFilm(DetailArtisFilmViewModel paramModel)
        {
            try
            {
                if (DetailArtisFilmDataAccess.Insert(paramModel))
                {
                    return Json(new { success = true, message = "berhasil!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = FilmDataAccess.Message }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Add()
        {
            ViewData["Negara"] = NegaraDataAccess.GetAll();
            return PartialView("Add");
        }

        [HttpPost]
        public ActionResult Add(ArtisViewModel paramModel)
        {
            paramModel.created_by = "admin";
            try
            {
                if (ArtisDataAccess.Insert(paramModel))
                {
                    return Json(new { success = true, message = "berhasil!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = FilmDataAccess.Message }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult List(int? paramPage, int paramPageSize, string paramSearch)
        {
            int countDataDb = ArtisDataAccess.GetCount(paramSearch);
            PagingModel_Artis pg = new PagingModel_Artis(countDataDb, paramPage, paramPageSize);
            ViewData["pg"] = pg;
            List<ArtisViewModel> listData = ArtisDataAccess.GetList(paramSearch, ((pg.CurrentPage - 1) * pg.PageSize), pg.PageSize);
            foreach (var item in listData)
            {
                int angka = Convert.ToInt32(item.bayaran);
                item.bayaran_str = String.Format(CultureInfo.CreateSpecificCulture("id-id"), "Rp. {0:N}", angka);
            }
            return PartialView("List", listData);
        }
        
        public ActionResult CheckNamaArtis(string nama, string jk, int idN)
        {
            if (ArtisDataAccess.CheckArtis(nama, jk, idN))
            {
                return Json(new { success = true, message = "none" }, JsonRequestBehavior.AllowGet);//belum ada
            }
            else
            {
                return Json(new { success = false, message = "exist" }, JsonRequestBehavior.AllowGet);//sudah ada
            }
        }
    }
}

01.Cinema_Info.Web/Controllers/FilmController.cs
using _02.Cinema_info.DataAccess;
using _03.Cinema_Info.ViewModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _01.Cinema_Info.Web.Controllers
{
    public class FilmController : Controller
    {
        // GET: Film
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create() 
        {
            return PartialView("Create");
        }

        [HttpPost]
        public ActionResult Create(FilmViewModel paramModel)
        {
            paramModel.created_by = "admin";
            try
            {
                if (FilmDataAccess.Insert(paramModel))
                {
                    return Json(new { success = true, message = "berhasil!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = FilmDataAccess.Message }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult List(int? paramPage, int paramPageSize, string paramSearch)
        {
            int countDataDb = FilmDataAccess.GetCount(paramSearch);
            PagingModel_Film pg = new PagingModel_Film(countDataDb, paramPage, paramPageSize);
            ViewData["pg"] = pg;
            List<FilmViewModel> listData = FilmDataAccess.GetList(paramSearch, ((pg.CurrentPage - 1) * pg.PageSize), pg.PageSize);
            foreach (var item in listData)
            {
                int angka = Convert.ToInt32(item.pendapatan);
                item.pendapatan_str = String.Format(CultureInfo.CreateSpecificCulture("id-id"), "Rp. {0:N}", angka);
            }
            return PartialView("List", listData);
        }

        public ActionResult CheckKodeFilm(string kode)
        {
            if (FilmDataAccess.CheckKodeFilm(kode.ToUpper()))
            {
                return Json(new { success = true, message = "none" }, JsonRequestBehavior.AllowGet);//belum ada
            }
            else
            {
                return Json(new { success = false, message = "exist" }, JsonRequestBehavior.AllowGet);//sudah ada
            }
        }

        public ActionResult CheckJudulFilm(string judul)
        {
            if (FilmDataAccess.CheckJudulFilm(judul.ToUpper()))
            {
                return Json(new { success = true, message = "none" }, JsonRequestBehavior.AllowGet);//belum ada
            }
            else
            {
                return Json(new { success = false, message = "exist" }, JsonRequestBehavior.AllowGet);//sudah ada
            }
        }

        public ActionResult Detail(int idFilm)
        {
            ViewData["artis"] = DetailArtisFilmDataAccess.GetListByIdFilm(idFilm);
            FilmViewModel film = FilmDataAccess.GetById(idFilm);
            int angka = Convert.ToInt32(film.pendapatan);
            film.pendapatan_str = String.Format(CultureInfo.CreateSpecificCulture("id-id"), "Rp. {0:N}", angka);
            return PartialView("Detail", film);
        }
    }
}

01.Cinema_Info.Web/Views/Film/Create.cshtml
@model _03.Cinema_Info.ViewModel.FilmViewModel

<div class="row">
    @*<div class="col-md-3">
        <div class="form-group">
            <label class="label-form">Kode Film *</label>
            <div class="input-group">
                <input autocomplete="off" type="text" name="kode_film" class="form-control required" id="kode_film"
                       data-warning-target="kode_film-warning" onkeyup="checkKodeFilm()" />
            </div>
            <span id="kode_film-warning" style="color:red ; font-size: 12px"></span>
        </div>
    </div>*@

    <div class="col">
        <div class="form-group">
            <label class="label-form">Judul Film *</label>
            <div class="input-group">
                <input type="text"  name="nama_film" class="form-control required" id="nama_film"
                       data-warning-target="nama_film-warning" />
            </div>
            <span id="nama_film-warning" style="color:red ; font-size: 12px"></span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <label class="label-form">Pendapatan *</label>
            <div class="input-group">
                <input type="text"  name="pendapatan" class="form-control required" id="pendapatan"
                       data-warning-target="pendapatan-warning" />
            </div>
            <span id="pendapatan-warning" style="color:red ; font-size: 12px"></span>
        </div>
    </div>

    <div class="col">
        <div class="form-group">
            <label class="label-form">Jumlah Nominasi Film *</label>
            <div class="input-group">
                <input type="text"  name="nominasi" class="form-control required" id="nominasi"
                       data-warning-target="nominasi-warning" />
            </div>
            <span id="nominasi-warning" style="color:red ; font-size: 12px"></span>
        </div>
    </div>

    <div class="col">
        <div class="form-group">
            <label class="label-form">Tanggal Rilis *</label>
            <div class="input-group">
                <input type="text" readonly name="tahun_rilis" class="datepicker form-control required" id="tahun_rilis"
                       data-date-end-date="0d" data-warning-target="tahun_rilis-warning" />
            </div>
            <span id="tahun_rilis-warning" style="color:red ; font-size: 12px"></span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <a href="#" class="btn btn-primary" id="" onclick="submitForm()">Tambahkan</a>
    </div>
</div>

<script type="text/javascript">
    var Vocab = Vocab || {};
    Vocab.InputRequired = "This input is required";
    Vocab.InputFormatFalse = "Tidak sesuai format";

    $(document).ready(function () {
        var options = {
            format: 'MM dd, yyyy',
            todayHighlight: true,
            autoclose: true,
            orientation: "left top"
        };
        $(".datepicker").datepicker(options);
    });

    function submitForm() {
        if (CheckValidation()) {
            var pdpt = TrimRupiah();
            var item = {
                //kode_film : $("#kode_film").val(),
                nama_film: $("#nama_film").val(),
                pendapatan: pdpt,
                nominasi: $("#nominasi").val(),
                tahun_rilis: $("#tahun_rilis").val(),
            };
            $.ajax({
                url: '@Url.Action("Create","Film")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        ShowList(1, "");
                        swal("Berhasil Ditambahkan!", {
                            icon: "success",
                        });
                        $("#kt_modal_4").modal("hide");
                    }
                    else {
                        swal("Gagal!", {
                            icon: "error",
                        });
                    }
                }
            });
        }

    }

    function CheckValidation() {
        var valid = true;

        $(".required").each(function (i) {
            if ($(this).val() === "" || $(this).val() == null) {
                $("#" + $(this).data("warning-target")).text(Vocab.InputRequired);
                valid = false;
            } else {
                $("#" + $(this).data("warning-target")).text("");
            }
        })

        valid = valid && checkJudulFilm();

        return valid;
    }

    function checkJudulFilm() {
        var jdl = $("#nama_film").val();
        var result = true;
        $.ajax({
            async: false,
            url: '@Url.Action("CheckJudulFilm", "Film")',
            type: 'get',
            data: { judul: jdl },
            success: function (result) {
                if (result.success) {
                    $("#nama_film-warning").text("");
                }
                else {
                    $("#nama_film-warning").text("sudah ada");
                }
            }
        });

        if ($("#nama_film-warning").text() == "") {
            result = true;
        }
        else {
            result = false;
        }
        return result;
    }

    var rupiah = document.getElementById('pendapatan');

    rupiah.addEventListener('keyup', function (e) {
		// tambahkan 'Rp.' pada saat form di ketik
		// gunakan fungsi formatRupiah() untuk mengubah angka yang di ketik menjadi format angka
        rupiah.value = formatRupiah(this.value, 'Rp. ');
    });

    /* Fungsi formatRupiah */
    function formatRupiah(angka, prefix) {
		var number_string = angka.replace(/[^,\d]/g, '').toString(),
		split   		= number_string.split(','),
		sisa     		= split[0].length % 3,
		rupiah     		= split[0].substr(0, sisa),
		ribuan     		= split[0].substr(sisa).match(/\d{3}/gi);

		// tambahkan titik jika yang di input sudah menjadi angka ribuan
		if(ribuan){
			separator = sisa ? '.' : '';
			rupiah += separator + ribuan.join('.');
		}

		rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
        return prefix == undefined ? rupiah : (rupiah ? 'Rp. ' + rupiah : '');
    }

    function TrimRupiah() {
        //Rp. 60.000.000
        var str = $("#pendapatan").val(); 
        var res = str.replace(/R|p|\.| /g, "");

        //var res = str.replace("R", "");
        //var result = res;

        //res = result.replace("p", "");
        //result = res;

        //res = result.replace(/\./g, "");
        //result = res;

        //res = result.replace(" ", "");
        //result = res;        

        //return result;
        return res;
    }
</script>

01.Cinema_Info.Web/Views/Film/Detail.cshtml
@model _03.Cinema_Info.ViewModel.FilmViewModel

@{
    IEnumerable<_03.Cinema_Info.ViewModel.DetailArtisFilmViewModel> artis = (IEnumerable<_03.Cinema_Info.ViewModel.DetailArtisFilmViewModel>)ViewData["artis"];
}


<div class="row">
    <div class="col-md-6">
        <div class="kt-widget4 kt-widget4--sticky">
            <div class="kt-widget4__items kt-widget4__items--bottom kt-portlet__space-x kt-margin-b-20">
                <div class="kt-widget4__item">
                    <div class="kt-widget4__info">
                        <a href="#" class="kt-widget4__title">
                            @Model.nama_film
                        </a>
                    </div>
                </div>
                <div class="kt-widget4__item">
                    <div class="kt-widget4__info">
                        <a href="#" class="kt-widget4__text">
                            Dirilis pada @Model.tahun_rilis.ToString("dd MMMM, yyyy")
                        </a>
                    </div>
                </div>
                <div class="kt-widget4__item">
                    <div class="kt-widget4__info">
                        <a href="#" class="kt-widget4__text">
                            Pendapatan sebesar @Model.pendapatan_str
                        </a>
                    </div>
                </div>
                <div class="kt-widget4__item">
                    <div class="kt-widget4__info">
                        <a href="#" class="kt-widget4__text">
                            Dinominasikan sebanyak @Model.nominasi kali
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <ul class="nav nav-tabs nav-tabs-line" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#kt_portlet_base_demo_1_tab_content" role="tab">
                    Cast
                </a>
            </li>
        </ul>
        <div class="kt-widget4 kt-widget4--sticky">
            <div class="kt-widget4">
                <div class="tab-content">
                    <div class="tab-pane active" id="kt_portlet_base_demo_1_tab_content" role="tabpanel">
                        <div class="row">
                            @if (artis.Count() != 0)
                            {
                                foreach (var item in artis)
                                {
                                    <div class="col">
                                        <div class="kt-widget4__item">
                                            <div class="kt-widget4__info">
                                                <a href="#" class="kt-widget4__username">
                                                    @item.nama_artis
                                                </a>
                                                <p class="kt-widget4__text">
                                                    sebagai @item.peran
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

01.Cinema_Info.Web/Views/Film/Index.cshtml
@{
    ViewBag.Title = "Movie Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">Movie</h3>

        </div>
        <div class="kt-subheader__toolbar">
            <a href="#" class="btn btn-label-brand btn-bold" onclick="AddFilm()">
                Tambahkan Data Film
            </a>
        </div>
    </div>
</div>

<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div id="content_page">

    </div>
</div>

<div class="modal fade" id="kt_modal_4" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="kt_modal_4_label">New message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body" id="kt_modal_4_body">

            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="kt_modal_42" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="kt_modal_42_label">New message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body" id="kt_modal_42_body">

            </div>

        </div>
    </div>
</div>


@section Scripts
{
    <script type="text/javascript">
        var progHtml = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar progress-bar-striped" style="width:100%"/></div></div>';
        var Last_Record_Per_Page;
        var rpp;

        $(document).ready(function () {
            ShowList(1, "");
        });

        function AddFilm() {
            $("#kt_modal_4").modal("show");
            $("#kt_modal_4_label").text("Tambahkan Film");
            $("#kt_modal_4_body").html(progHtml);
            $.ajax({
                url: '@Url.Action("Create","Film")',
                type: 'get',
                success: function (result) {
                    $("#kt_modal_4_body").html(result);
                }
            });
        }

        function ShowList(pPage, pSearch) {
            Last_Record_Per_Page = rpp == undefined ? 20 : rpp;
            $("#content_page").html(progHtml);
            $.ajax({
                url: '@Url.Action("List","Film")',
                type: 'get',
                data: {
                    paramPage: pPage,
                    paramPageSize: Last_Record_Per_Page,
                    paramSearch: pSearch,
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert('An error occurred... Look at the console (F12 or Ctrl+Shift+I, Console tab) for more information!');

                    $('#content_page').html('<p>status code: '+jqXHR.status+'</p><p>errorThrown: ' + errorThrown + '</p><p>jqXHR.responseText:</p><div>'+jqXHR.responseText + '</div>');
                    console.log('jqXHR:');
                    console.log(jqXHR);
                    console.log('textStatus:');
                    console.log(textStatus);
                    console.log('errorThrown:');
                    console.log(errorThrown);
                },

                success: function (result) {
                    $("#content_page").html(result);
                }
            });
        }

        $("#txt-search").keypress(function (event) {
            if (event.keyCode == 13) {
                $("#btn-search").click();
                return false;
            }
        });

        $("#btn-search").click(function () {
            ShowList(1, $("#txt-search").val());
        });

        $("#btn-reset").click(function () {
            $("#txt-search").val("");
            ShowList(1, "");
        });
    </script>
}

<style>
    .example-open .modal-backdrop {background-color:red;}
</style>

01.Cinema_Info.Web/Views/Film/List.cshtml
@model IEnumerable<_03.Cinema_Info.ViewModel.FilmViewModel>

@using _03.Cinema_Info.ViewModel;

@{
    PagingModel_Film _page = (PagingModel_Film)ViewData["pg"];
}

@if (Model.Count() != 0)
{
    foreach (var item in Model)
    {
        <div class="kt-portlet kt-portlet--height-fluid">
            <div class="kt-portlet__head kt-portlet__head--noborder">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        @item.nama_film
                    </h3>
                </div>
                <div class="kt-portlet__head-toolbar">
                    <div class="kt-widget__contact">
                        @*<span class="kt-widget__label">@item.tahun_rilis.ToString("yyyy")</span>*@
                    </div>
                </div>
            </div>
            <div class="kt-portlet__body">

                <!--begin::Widget -->
                <div class="kt-widget kt-widget--user-profile-2">
                    <div class="kt-widget__head">
                        <div class="kt-widget__info">
                            <a class="kt-widget__desc" href="#">
                            </a>
                        </div>
                    </div>
                    <div class="kt-widget__body">
                        <div class="kt-widget__item">
                            <div class="kt-widget__contact">
                                <span class="kt-widget__label">Pendapatan :</span>
                                <span class="kt-widget__data">
                                    @item.pendapatan_str
                                </span>
                            </div>
                            <div class="kt-widget__contact">
                                <span class="kt-widget__label">Tanggal Rilis :</span>
                                <span class="kt-widget__data">
                                    @item.tahun_rilis.ToString("dd MMMM, yyyy")
                                </span>
                            </div>
                            <div class="kt-widget__contact" hidden>
                                <span class="kt-widget__label">Produser :</span>
                                <span class="kt-widget__data">
                                    -
                                </span>
                            </div>
                            <div class="kt-widget__contact" hidden>
                                <span class="kt-widget__label">Artis :</span>
                                <span class="kt-widget__data">
                                    -
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="kt-portlet__foot--sm">
                        <div class="kt-portlet__head-toolbar">
                            <div class="kt-portlet__head-actions">
                                <a href="#" class="btn btn-outline-warning btn-sm kt-margin-5" onclick="AddArtis(@item.id_film_pk)">
                                    Tambahkan Artis
                                </a>
                                <a href="#" class="btn btn-outline-brand btn-sm kt-margin-5" onclick="Detail(@item.id_film_pk)">
                                    Detail
                                </a>

                            </div>
                        </div>
                    </div>
                </div>

                <!--end::Widget -->
            </div>
        </div>

    }
}
else
{
    <div class="kt-portlet kt-portlet--height-fluid">
        <div class="kt-portlet__head kt-portlet__head--noborder">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    Data Kosong
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
            </div>
        </div>
    </div>
}

<div class="kt-portlet kt-portlet--height-fluid">
    <div class="kt-portlet__body kt-portlet__body--fit">
        <table style="width:100%">
            <tr>
                @* ini untuk paging *@
                @if (_page != null)
                {
                    if (_page.EndPage > 1)
                    {
                        <td style="background-color:white;border:none">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2"></div>
                                <div class="col-auto">
                                    <ul class="pagination" style="margin:0px">
                                        @if (_page.CurrentPage > 1)
                                        {
                                            <li>
                                                <a class="btn btn-brand btn-elevate btn-icon-sm"
                                                   href="#" onclick="PageMove((@_page.CurrentPage - 1));">
                                                    Previous
                                                </a>
                                            </li>
                                        }

                                        @if (_page.CurrentPage < _page.TotalPages)
                                        {
                                            <li>
                                                <a class="btn btn-brand btn-elevate btn-icon-sm"
                                                   href="#" onclick="PageMove(@_page.CurrentPage + 1);">
                                                    Next
                                                </a>
                                            </li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </td>
                    }
                }
            </tr>
        </table>
    </div>
</div>


<script type="text/javascript">

    $(document).ready(function () {
    });

    function PageMove(pPage) {
        ShowListCreated(pPage, $("#txt-search").val());
    };

    function Detail(pIdFilm) {
        $("#kt_modal_4").modal("show");
        $("#kt_modal_4_label").text("Detail Film");
        $("#kt_modal_4_body").html(progHtml);
        $.ajax({
            url: '@Url.Action("Detail","Film")',
            type: 'get',
            data: { idFilm: pIdFilm },
            success: function (result) {
                $("#kt_modal_4_body").html(result);
            }
        });
    }
    function AddArtis(pIdFilm) {
        $("#kt_modal_4").modal("show");
        $("#kt_modal_4_label").text("Tambahkan Artis");
        $("#kt_modal_4_body").html(progHtml);
        $.ajax({
            url: '@Url.Action("AddToFilm","Artis")',
            type: 'get',
            data: { idFilm: pIdFilm },
            success: function (result) {
                $("#kt_modal_4_body").html(result);
            }
        });
    }

    function DeleteDisposisi(idDisposisi) {
        swal({
            title: "Anda yakin?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                $.ajax({
                    url: '/Disposisi/Delete',
                    type: 'get',
                    data: { idDispo: idDisposisi },
                    success: function (result) {
                        if (result.success) {
                            swal("Item berhasil dihapus!", {
                                icon: "success",
                            });
                            if ($("#id_tahta").val() == 1) {
                                ShowListDisposisi(pageNow, $("#txt-search").val());
                            }
                            else {
                                ShowListCreated(pageNow, $("#txt-search").val());
                            }
                        }
                        else {
                            swal("Item gagal dihapus!", {
                                icon: "error",
                            });
                        }

                    }
                });
            }
        });
    }
    
</script>