01.Cinema_Info.Web/Controllers/NegaraController.cs
using _02.Cinema_info.DataAccess;
using _03.Cinema_Info.ViewModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _01.Cinema_Info.Web.Controllers
{
    public class NegaraController : Controller
    {
        // GET: Negara
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            return PartialView("Add");
        }

        [HttpPost]
        public ActionResult Add(NegaraViewModel paramModel)
        {
            paramModel.created_by = "admin";
            try
            {
                if (NegaraDataAccess.Insert(paramModel))
                {
                    return Json(new { success = true, message = "berhasil!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = FilmDataAccess.Message }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult List(int? paramPage, int paramPageSize, string paramSearch)
        {
            int countDataDb = NegaraDataAccess.GetCount(paramSearch);
            PagingModel_Negara pg = new PagingModel_Negara(countDataDb, paramPage, paramPageSize);
            ViewData["pg"] = pg;
            List<NegaraViewModel> listData = NegaraDataAccess.GetList(paramSearch, ((pg.CurrentPage - 1) * pg.PageSize), pg.PageSize);
            return PartialView("List", listData);
        }

        public ActionResult CheckNegara(string nama)
        {
            if (NegaraDataAccess.CheckNegara(nama))
            {
                return Json(new { success = true, message = "none" }, JsonRequestBehavior.AllowGet);//belum ada
            }
            else
            {
                return Json(new { success = false, message = "exist" }, JsonRequestBehavior.AllowGet);//sudah ada
            }
        }
    }
}

01.Cinema_Info.Web/Views/Negara/Add.cshtml
<div class="row">
    <div class="col">
        <div class="form-group">
            <label class="label-form">Nama Negara *</label>
            <div class="input-group">
                <input type="text" name="nama_negara" class="form-control required" id="nama_negara"
                       data-warning-target="nama_negara-warning" />
            </div>
            <span id="nama_negara-warning" style="color:red ; font-size: 12px"></span>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-3">
        <a href="#" class="btn btn-primary" id="" onclick="submitNegara()">Tambahkan</a>
    </div>
</div>

<script type="text/javascript">
    var Vocab = Vocab || {};
    Vocab.InputRequired = "This input is required";

    $(document).ready(function () {
    });

    function submitNegara() {
        if (CheckValidation()) {
            var item = {
                nama_negara: $("#nama_negara").val(),
            };
            $.ajax({
                url: '@Url.Action("Add","Negara")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        ShowList(1, "");
                        swal("Berhasil Ditambahkan!", {
                            icon: "success",
                        });
                        $("#kt_modal_4").modal("hide");
                    }
                    else {
                        swal("Gagal!", {
                            icon: "error",
                        });
                    }
                }
            });
        }

    }

    function CheckValidation() {
        var valid = true;

        $(".required").each(function (i) {
            if ($(this).val() === "" || $(this).val() == null) {
                $("#" + $(this).data("warning-target")).text(Vocab.InputRequired);
                valid = false;
            } else {
                $("#" + $(this).data("warning-target")).text("");
            }
        })

        valid = valid && CheckNegara();

        return valid;
    }

    function CheckNegara() {
        var nm = $("#nama_negara").val();
        var result = true;
        $.ajax({
            async: false,
            url: '@Url.Action("CheckNegara", "Negara")',
            type: 'get',
            data: { nama: nm},
            success: function (result) {
                if (result.success) {
                    $("#nama_negara-warning").text("");
                }
                else {
                    $("#nama_negara-warning").text("nama negara sudah pernah ditambahkan");
                }
            }
        });

        if ($("#nama_negara-warning").text() == "") {
            result = true;
        }
        else {
            result = false;
        }
        return result;
    }
    
</script>

01.Cinema_Info.Web/Views/Negara/Index.cshtml
@{
    ViewBag.Title = "Negara";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">Negara</h3>
        </div>
        <div class="kt-subheader__toolbar">
            <a href="#" class="btn btn-label-brand btn-bold" onclick="AddNegara()">
                Tambahkan Negara
            </a>
        </div>
    </div>
</div>

<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div id="content_page">

    </div>
</div>

<div class="modal fade" id="kt_modal_4" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="kt_modal_4_label">New message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body" id="kt_modal_4_body">

            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="kt_modal_42" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="kt_modal_42_label">New message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body" id="kt_modal_42_body">

            </div>

        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        var progHtml = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar progress-bar-striped" style="width:100%"/></div></div>';
        var Last_Record_Per_Page;
        var rpp;

        $(document).ready(function () {
            ShowList(1, "");
        });

        function AddNegara() {
            $("#kt_modal_4").modal("show");
            $("#kt_modal_4_label").text("Tambahkan Artis");
            $("#kt_modal_4_body").html(progHtml);
            $.ajax({
                url: '@Url.Action("Add","Negara")',
                type: 'get',
                success: function (result) {
                    $("#kt_modal_4_body").html(result);
                }
            });
        }

        function ShowList(pPage, pSearch) {
            Last_Record_Per_Page = rpp == undefined ? 20 : rpp;
            $("#content_page").html(progHtml);
            $.ajax({
                url: '@Url.Action("List","Negara")',
                type: 'get',
                data: {
                    paramPage: pPage,
                    paramPageSize: Last_Record_Per_Page,
                    paramSearch: pSearch,
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert('An error occurred... Look at the console (F12 or Ctrl+Shift+I, Console tab) for more information!');

                    $('#content_page').html('<p>status code: '+jqXHR.status+'</p><p>errorThrown: ' + errorThrown + '</p><p>jqXHR.responseText:</p><div>'+jqXHR.responseText + '</div>');
                    console.log('jqXHR:');
                    console.log(jqXHR);
                    console.log('textStatus:');
                    console.log(textStatus);
                    console.log('errorThrown:');
                    console.log(errorThrown);
                },

                success: function (result) {
                    $("#content_page").html(result);
                }
            });
        }

        $("#txt-search").keypress(function (event) {
            if (event.keyCode == 13) {
                $("#btn-search").click();
                return false;
            }
        });

        $("#btn-search").click(function () {
            ShowList(1, $("#txt-search").val());
        });

        $("#btn-reset").click(function () {
            $("#txt-search").val("");
            ShowList(1, "");
        });
    </script>
}

01.Cinema_Info.Web/Views/Negara/List.cshtml
@model IEnumerable<_03.Cinema_Info.ViewModel.NegaraViewModel>

@using _03.Cinema_Info.ViewModel;

@{
    PagingModel_Negara _page = (PagingModel_Negara)ViewData["pg"];
}

@if (Model.Count() != 0)
{
    foreach (var item in Model)
    {
        <div class="kt-widget29__content kt-margin-t-0 kt-padding-t-0">
            <h6 class="kt-widget29__subtitle">
                <a href="#" class="kt-widget__data" onclick="">@item.nama_negara</a>
            </h6>
        </div>
        <br />
    }
}
else
{
    <div class="kt-portlet kt-portlet--height-fluid">
        <div class="kt-portlet__head kt-portlet__head--noborder">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    Data Kosong
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
            </div>
        </div>
    </div>
}

<div class="kt-portlet kt-portlet--height-fluid">
    <div class="kt-portlet__body kt-portlet__body--fit">
        <table style="width:100%">
            <tr>
                @* ini untuk paging *@
                @if (_page != null)
                {
                    if (_page.EndPage > 1)
                    {
                        <td style="background-color:white;border:none">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2"></div>
                                <div class="col-auto">
                                    <ul class="pagination" style="margin:0px">
                                        @if (_page.CurrentPage > 1)
                                        {
                                            <li>
                                                <a class="btn btn-brand btn-elevate btn-icon-sm"
                                                   href="#" onclick="PageMove((@_page.CurrentPage - 1));">
                                                    Previous
                                                </a>
                                            </li>
                                        }

                                        @if (_page.CurrentPage < _page.TotalPages)
                                        {
                                            <li>
                                                <a class="btn btn-brand btn-elevate btn-icon-sm"
                                                   href="#" onclick="PageMove(@_page.CurrentPage + 1);">
                                                    Next
                                                </a>
                                            </li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </td>
                    }
                }
            </tr>
        </table>
    </div>
</div>


<script type="text/javascript">

    $(document).ready(function () {

    });

    function PageMove(pPage) {
        ShowList(pPage, $("#txt-search").val());
    };

    function DetailPenerima(pIdDispo) {
        $("#kt_modal_4").modal("show");
        $("#kt_modal_4_label").text("Detail Penerima Disposisi");
        $("#kt_modal_4_body").html(progHtml);
        $.ajax({
            url: '@Url.Action("DetailPenerima","Disposisi")',
            type: 'get',
            data: { idDisposisi: pIdDispo },
            success: function (result) {
                $("#kt_modal_4_body").html(result);
            }
        });
    }

</script>